
;; going to try to do the same thing now , but with sdl3 libraries 
;; sudo apt install libsdl3-dev
;; so we have sdl3 libraries
;; on my system this is located at shared library { /usr/lib/x86_64-linux-gnu/libSDL3.so }
;; the header files are  { /usr/include/SDL3/SDL.h }
;;
;; this all loads fine all need to do is
;; (ql:quickload :brut) ;; this file will be compiled along with rest of stuff
;; use a separate package to do autowrap stuff
;; (ql:quickload :cl-autowrap)
;; (ql:quickload :cl-autowrap/libffi)
;; (ql:quickload :uiop)
;; (sb-posix:getcwd) ;; what is current directory
;; (sb-posix:chdir "../") ;; as example

;;SB-IMPL::*ALL-PACKAGES*

;; (ql:quickload :cl-autowrap)  but package is called autowrap??
(defpackage :sdl3.test
  (:use #:cl #:autowrap))

(in-package :sdl3.test)

(eval-when (:compile-toplevel :load-toplevel :execute)
  (cffi-sys:%load-foreign-library
   :libsdl (pathname "/usr/lib/x86_64-linux-gnu/libSDL3.so")))

;; toplevel macro - cant make exclude definitions nice in any way - must be lilterals strings??!?
(c-include "/usr/include/SDL3/SDL.h"
               :spec-path (merge-pathnames "./sdl3spec/" (asdf-path 'brut))
	       :exclude-definitions ("SDL-I-OVPRINTF"
				     "SDL-LOG-MESSAGE-V"
				     "SDL-SET-ERROR-V"
				     "SDL-VASPRINTF"
				     "SDL-VSNPRINTF"
				     "SDL-VSSCANF"
				     "SDL-VSWPRINTF"
				     "VA-LIST"
				     "VFWPRINTF"
				     "VFWSCANF"
				     "VSWPRINTF" 
				     "VWSCANF"
				     "WCSTOLD"
				     "_FLOAT64X"))

;; (c-include "/usr/include/SDL3/SDL_init.h"
;;            :spec-path (merge-pathnames "./sdl3spec/" (asdf-path 'brut)))

;; (c-include "/usr/include/SDL3/SDL_video.h"
;;            :spec-path (merge-pathnames "./sdl3spec/" (asdf-path 'brut)))


;; ===== a simple example of using sdl3 =======
;; FLAG | FLAG is logior logical inclusive or
;; ! is lognot 
(defun fred ()
  (let ((window nil)
	(window-width 640)
	(window-height 480)
	(result (sdl-init (logior +sdl-init-video+ +sdl-init-events+))))
    (format t "result ~a~%" result)
    (setq window (sdl-create-window "SDL3 window" window-width window-height 0))
    (sdl-show-window window)
    (sleep 5)
    (sdl-quit)))



  ;;  if (!SDL_Init(SDL_INIT_VIDEO | SDL_INIT_EVENTS))
  ;; {
  ;;   return -1;
  ;; }

  ;; SDL_Quit();



;; ;; now its saying :say is undefined
;; (defun :say (x) (format t "~a~%" x))

;; (defun fred ()
;;   (let ((foo (get-foo)))
;;     (:say foo)
;;     (:say (foo-t.a foo))
;;     (:say (foo-t.x[].a foo 0))
;;     (:say (foo-t.x[].f foo 1))
;;     (:say (foo-t.x[].b0 foo 0))
;;     (:say (foo-t.x[].b1 foo 0))
;;     (:say (cffi-sys:%mem-ref (ptr foo) :unsigned-char (+ 16 24)))
;;     (setf (foo-t.x[].b0 foo 0) #b01)
;;     (setf (foo-t.x[].b1 foo 0) #b110)
;;     (print-bits foo)
;;     (free-foo foo)))


;; ============ old example code from cl-autowrap =================

;; +(or) means following s expression will NOT be evaluated
;; so this code sorta sits here completely inert and unusable
;; perhaps its for an example
;; #+(or)
;; (eval-when (:compile-toplevel :load-toplevel :execute)
;;   (cffi-sys:%load-foreign-library
;;    :libtest (merge-pathnames "libtest.so" (asdf-path 'cl-autowrap-test))))
;;
;; #+(or)
;; (c-include '(cl-autowrap-test "test.h")
;;            :spec-path '(cl-autowrap-test))
;;
;; make sure we are in working directory - this can get messy
;; (uiop/os:chdir "../working/")
;; (uiop/os:getcwd) ;; #P"/home/terry/code/common-lisp/sdl3/working/"
;;

;; do i need to register cl-autowrap-test as an asdf ? 
;; lets load the libtest.so that was generated by running gcc command at top of test.c
;; (eval-when (:compile-toplevel :load-toplevel :execute)
;;   (cffi-sys:%load-foreign-library
;;    :libtest (pathname "/home/terry/code/common-lisp/sdl3/cl-autowrap-test/libtest.so")))

;;(merge-pathnames "libtest.so" (uiop/os:getcwd))))
;; (eval-when (:compile-toplevel :load-toplevel :execute)
;;   (c-include '(brut "brut.h) 
;;            :spec-path (merge-pathnames "../spec/" (asdf-path 'brut))))

;;(merge-pathnames "brut.h" (asdf-path 'brut))

;; (c-include '(brut "brut.h")
;; 	   :spec-path (merge-pathnames "spec" (asdf-path 'brut)))


;; (c-include "brut.h";;(pathname "/home/terry/code/common-lisp/sdl3/cl-autowrap-test/brut.h")
;; 	   :spec-path "/home/terry/code/common-lisp/sdl3/spec/")

;; (c-include "test.h" ;; (merge-pathnames "test.h" (uiop/os:getcwd)) 
;;            :spec-path #P"/home/terry/code/common-lisp/sdl3/test/spec")

;; (merge-pathnames "spec" (uiop/os:getcwd)))

	   ;;(concatenate 'string *default-pathname-defaults* "./spec/"))
 ;; (concatenate 'string (sb-posix:getcwd) "/spec"))

#+(or)
(let ((foo (get-foo)))
  (:say foo)
  (:say (foo-t.a foo))
  (:say (foo-t.x[].a foo 0))
  (:say (foo-t.x[].f foo 1))
  (:say (foo-t.x[].b0 foo 0))
  (:say (foo-t.x[].b1 foo 0))
  (:say (cffi-sys:%mem-ref (ptr foo) :unsigned-char (+ 16 24)))
  (setf (foo-t.x[].b0 foo 0) #b01)
  (setf (foo-t.x[].b1 foo 0) #b110)
  (print-bits foo)
  (free-foo foo))


#|

(in-package :brut.test)
(fred)

or possibly (brut.test::fred) 

we get following results

b0 = 1, b1 = 6
#<FOO-T {#X64E2DAD7FF10}>
1
42
0.0
2
5
22
; No value				;

|#
